### ISSUE TITLE
cutting out LEDs

### ISSUE THREAD

**Issue by CatherineTaelman** [jerabaul29/OpenMetBuoy-v2021a#30]
You indicate to cut out the 'power LED' to save the batteries. Does it make sense to also cut out the other LEDs? Or are they rather useful to check that the instrument is working properly and don't consume so much power anyway?

**Comment by jerabaul29** [comment]
(but cut the LEDs on the qwiic switch, these are some always on that use quite a bit :) ).

**Comment by jerabaul29** [comment]
Updated the doc, closing.
