### ISSUE TITLE
share the cruiser setup, here or at another location?

### ISSUE THREAD

**Issue by jerabaul29** [jerabaul29/OpenMetBuoy-v2021a#41]
@gauteh if you want to share the "cruiser" setup, either here or at another location, with some recipe on how to set up, that would be great :) .

**Comment by gauteh** [comment]
Yeah, it was basically a dedicated ssh server with mosh set up outside any VPN for more robust connection from a ship. with everything useful installed. also recommend `tldr` for command cheat sheet with poor connection. nothing more special than that!
