### ISSUE TITLE
The Hammond box is a bit tight for upright antenna

### ISSUE THREAD

**Issue by gauteh** [jerabaul29/OpenMetBuoy-v2021a#48]
The suggested hammond box is a bit tight to get the antenna oriented upright: https://www.elfadistrelec.no/en/watertight-enclosure-smoked-lid-polycarbonate-120x120x80mm-clear-light-grey-hammond-1554p2gycl/p/30100709?q=&pos=2&origPos=52&origPageSize=50&track=true

**Comment by gauteh** [comment]
@benoitLD

**Comment by jerabaul29** [comment]
Yes, the RND box is a bit better. But note that it is not critical that the antenna is pointing completely upwards; 50 degrees upwards is fine enough :) .

**Comment by jerabaul29** [comment]
I will update the documentation

**Comment by gauteh** [comment]
:+1: probably worth keeping it 90deg in the first place, if it can be easily fixed with a higher box. a bit more margin.
