### ISSUE TITLE
standard set of scripts and tools for data collection: use the AWI deployment code when "battle tested"

### ISSUE THREAD

**Issue by jerabaul29** [jerabaul29/OpenMetBuoy-v2021a#59]

**Comment by tnn77** [comment]
Hi, @jerabaul29 
I just noticed this. I think res_fixes should be res_spectra in the below linked line. 
Thank you so much for this tool.

https://github.com/jerabaul29/OpenMetBuoy-v2021a/blob/main/legacy_firmware/utils/script_all_messages_to_dict.py#:~:text=%22spectra%22%5D%3A-,if%20crrt_entry.datetime_fix%20%3D%3D%20res_fixes%5B%2D1%5D.datetime_fix%3A,-pass

**Comment by jerabaul29** [comment]
thanks, will fix it now :) .
