### ISSUE TITLE
ISM330DHCX as a SF qwiic breakout 

### ISSUE THREAD

**Issue by jerabaul29** [jerabaul29/OpenMetBuoy-v2021a#61]
https://www.sparkfun.com/products/19764

Fyi @gauteh @jvoermans @tnn77 🎉

Todo: add as an alternative to the list of components.

**Comment by jvoermans** [comment]
Great! Getting more and more options to get them :)

**Comment by tnn77** [comment]
@jerabaul29 
this is good news. 

perhaps we can request this sensor to be included in the list of sensors an OLA can log.

**Comment by jerabaul29** [comment]
Also available as a 'micro', much more compact breakout :) .

https://bit.ly/3olfNev

**Comment by jerabaul29** [comment]
Added to the list of components, closing.
