### ISSUE TITLE
Size of buffer

### ISSUE THREAD

**Issue by bjorkqvi** [jerabaul29/OpenMetBuoy-v2021a#62]
How large is the buffer of the buoy? I'm thinking about a situation where the transmission is obstructed for some reason (e.g. snow) and the buoy cannot transmit. What is the recommended way to get the buffered data if the buoy is retrieved after such an incident?

**Comment by jerabaul29** [comment]
You can see it here:

https://github.com/jerabaul29/OpenMetBuoy-v2021a/blob/6044f294ff8fe0dd16f8a136d1fbe9ee66b6296a/legacy_firmware/firmware/standard_gps_waves_thermistors_drifter/params.h#L46

And here:

https://github.com/jerabaul29/OpenMetBuoy-v2021a/blob/6044f294ff8fe0dd16f8a136d1fbe9ee66b6296a/legacy_firmware/firmware/standard_gps_waves_thermistors_drifter/params.h#L145

These are the default values I have been using for quite some time, but you can always compile with other values - make sure to not exhaust RAM in this case :) .

Let me know if this is clear / answers what you want to know :) .
